--ROLES --
insert into roles(id_role,nombre) values(NEXTVAL('ROLES_SEQ'),'ROLE_ADMIN');
insert into roles(id_role,nombre) values(NEXTVAL('ROLES_SEQ'),'ROLE_USER');

--USUARIO 1--
INSERT INTO USUARIOS(ID_USUARIO,EMAIL,NOMBRE,NOMBRE_USUARIO,PASSWORD) VALUES (NEXTVAL('USUARIOS_SEQ'),'a@a.a','admin','admin','$2a$10$d6dVwkf9H4FpDqLZH9PIZ.Op9GEV4jMAu/J70Am61Ei6qbmDtiIUm');

--USUARIO 2--
INSERT INTO USUARIOS(ID_USUARIO,EMAIL,NOMBRE,NOMBRE_USUARIO,PASSWORD) VALUES (NEXTVAL('USUARIOS_SEQ'),'u@u.u','UserTest','UserTest','$2a$10$zGt1j8FNe8LR.VDVE1s0K.VDfuw3Yu.BVHuCEBYSbxMRDaAe6dhAy');


--ROLES DE USUARIO 1--
INSERT INTO USUARIOS_ROLES(ID_USUARIO,ID_ROL) VALUES (1,1);
INSERT INTO USUARIOS_ROLES(ID_USUARIO,ID_ROL) VALUES (1,2);

--ROLES DE USUARIO 1--
INSERT INTO USUARIOS_ROLES(ID_USUARIO,ID_ROL) VALUES (2,1);
INSERT INTO USUARIOS_ROLES(ID_USUARIO,ID_ROL) VALUES (2,2);

