
-------------------------------TIPOS INCIDENCIA-------------------------------------
INSERT INTO TIPOS_INCIDENCIA (ID_TIPO_INCIDENCIA,NOMBRE,PRIORIDAD,TIEMPO_ATENCION) VALUES (TIPOS_INCIDENCIA_SEQ.NEXTVAL,'total',1,1);
INSERT INTO TIPOS_INCIDENCIA (ID_TIPO_INCIDENCIA,NOMBRE,PRIORIDAD,TIEMPO_ATENCION) VALUES (TIPOS_INCIDENCIA_SEQ.NEXTVAL,'parcial',2,2);
INSERT INTO TIPOS_INCIDENCIA (ID_TIPO_INCIDENCIA,NOMBRE,PRIORIDAD,TIEMPO_ATENCION) VALUES (TIPOS_INCIDENCIA_SEQ.NEXTVAL,'esporadica',3,3);


