
-------------------------TIPOS DE CLIENTE-------------------------------------------
INSERT INTO TIPOS_CLIENTE (ID_TIPO_CLIENTE,NOMBRE,PRIORIDAD) VALUES (TIPOS_CLIENTE_SEQ.nextval,'Hospitales',1);
INSERT INTO TIPOS_CLIENTE (ID_TIPO_CLIENTE,NOMBRE,PRIORIDAD) VALUES (TIPOS_CLIENTE_SEQ.nextval,'Entidades gubernamentales',2);
INSERT INTO TIPOS_CLIENTE (ID_TIPO_CLIENTE,NOMBRE,PRIORIDAD) VALUES (TIPOS_CLIENTE_SEQ.nextval,'Personas VIP',3);
INSERT INTO TIPOS_CLIENTE (ID_TIPO_CLIENTE,NOMBRE,PRIORIDAD) VALUES (TIPOS_CLIENTE_SEQ.nextval,'Empresas de taxi',4);
INSERT INTO TIPOS_CLIENTE (ID_TIPO_CLIENTE,NOMBRE,PRIORIDAD) VALUES (TIPOS_CLIENTE_SEQ.nextval,'Persona normal',5);

