
------BORRAR PROCEDMIENTOS Y FUNCIONES------
DROP FUNCTION fn_agendar_orden;
DROP FUNCTION sp_main;

-----BORRAR TABLAS Y SECUENCIAS----
DROP TABLE USUARIOS_ROLES;
DROP TABLE ZONAS_CUADRILLAS;
DROP TABLE TIPOS_INCIDENCIA_TECNICOS;

DROP SEQUENCE USUARIOS_SEQ;
DROP TABLE USUARIOS;

DROP SEQUENCE ROLES_SEQ;
DROP TABLE ROLES;

DROP sequence AGENDAS_SEQ;
DROP TABLE AGENDAS;

DROP sequence ORDENES_ATENCION_SEQ;
DROP TABLE ORDENES_ATENCION;

DROP sequence INCIDENCIAS_SEQ;
DROP TABLE INCIDENCIAS;

DROP sequence CLIENTES_SEQ;
DROP TABLE CLIENTES;

DROP sequence TECNICOS_SEQ;
DROP TABLE TECNICOS;

DROP sequence CUADRILLAS_SEQ;
DROP TABLE CUADRILLAS;


DROP SEQUENCE TIPOS_CLIENTE_SEQ;
DROP TABLE TIPOS_CLIENTE;

DROP SEQUENCE ZONAS_SEQ;
DROP TABLE ZONAS;

DROP sequence TIPOS_INCIDENCIA_SEQ;
DROP TABLE TIPOS_INCIDENCIA;





