--------------------------------zonas-----------------------------------------
insert into zonas(id_zona,nombre) values (zonas_seq.nextval,'Valdivia');
insert into zonas(id_zona,nombre) values (zonas_seq.nextval,'Corral');
insert into zonas(id_zona,nombre) values (zonas_seq.nextval,'Lanco');
insert into zonas(id_zona,nombre) values (zonas_seq.nextval,'Los lagos');
insert into zonas(id_zona,nombre) values (zonas_seq.nextval,'Marfil');
insert into zonas(id_zona,nombre) values (zonas_seq.nextval,'Maviqina');
insert into zonas(id_zona,nombre) values (zonas_seq.nextval,'Paillaco');
insert into zonas(id_zona,nombre) values (zonas_seq.nextval,'Panquipulli');


---------------------INSERCION DATOS TIPO DE CLIENTE---------------
INSERT INTO TIPOS_CLIENTE (ID_TIPO_CLIENTE,NOMBRE,PRIORIDAD) VALUES (TIPOS_CLIENTE_SEQ.nextval,'Hospitales',1);
INSERT INTO TIPOS_CLIENTE (ID_TIPO_CLIENTE,NOMBRE,PRIORIDAD) VALUES (TIPOS_CLIENTE_SEQ.nextval,'Entidades gubernamentales',2);
INSERT INTO TIPOS_CLIENTE (ID_TIPO_CLIENTE,NOMBRE,PRIORIDAD) VALUES (TIPOS_CLIENTE_SEQ.nextval,'Personas VIP',3);
INSERT INTO TIPOS_CLIENTE (ID_TIPO_CLIENTE,NOMBRE,PRIORIDAD) VALUES (TIPOS_CLIENTE_SEQ.nextval,'Empresas de taxi',4);
INSERT INTO TIPOS_CLIENTE (ID_TIPO_CLIENTE,NOMBRE,PRIORIDAD) VALUES (TIPOS_CLIENTE_SEQ.nextval,'Persona normal',5);


----------------------------INCERCION CLIENTES----------------------------
INSERT INTO CLIENTES (ID_CLIENTE,NOMBRE,APELLIDO,IDENTIFICACION,ID_TIPO_CLIENTE,EMAIL,TELEFONO,DIRECCION,ID_ZONA)
    VALUES(CLIENTES_SEQ.NEXTVAL,'Jessica','Baquero',1015441322,5,'Jb@g.c','6665544','kr86B123-34',1);
INSERT INTO CLIENTES (ID_CLIENTE,NOMBRE,APELLIDO,IDENTIFICACION,ID_TIPO_CLIENTE,EMAIL,TELEFONO,DIRECCION,ID_ZONA)
    VALUES(CLIENTES_SEQ.NEXTVAL,'William','Aguilar',1015441330,2,'w@g.c','2343256','kr5Sur A4-89',3);
INSERT INTO CLIENTES (ID_CLIENTE,NOMBRE,APELLIDO,IDENTIFICACION,ID_TIPO_CLIENTE,EMAIL,TELEFONO,DIRECCION,ID_ZONA)
    VALUES(CLIENTES_SEQ.NEXTVAL,'Cristina','Cardozo',1015441345,3,'p@g.c','8432165','Cll falsa 123',5);


-------------------INSERCION DATOS TIPO DE DAÑO---------------------
INSERT INTO TIPO_INCIDENCIA (TIPO,NOMBRE,TIEMPO_ATENCION) VALUES ('total',1,SYSDATE);
INSERT INTO TIPO_INCIDENCIA (TIPO,NOMBRE,TIEMPO_ATENCION) VALUES ('parcial',2,SYSDATE);
INSERT INTO TIPO_INCIDENCIA (TIPO,NOMBRE,TIEMPO_ATENCION) VALUES ('esporadica',3,SYSDATE);

INSERT INTO TIPOS_INCIDENCIA (ID_TIPOS_INCIDENCIA,NOMBRE,PRIORIDAD,TIEMPO_ATENCION) VALUES (TIPOS_INCIDENCIA_SEQ.NEXTVAL,'total',1,1);
INSERT INTO TIPOS_INCIDENCIA (ID_TIPOS_INCIDENCIA,NOMBRE,PRIORIDAD,TIEMPO_ATENCION) VALUES (TIPOS_INCIDENCIA_SEQ.NEXTVAL,'parcial',2,2);
INSERT INTO TIPOS_INCIDENCIA (ID_TIPOS_INCIDENCIA,NOMBRE,PRIORIDAD,TIEMPO_ATENCION) VALUES (TIPOS_INCIDENCIA_SEQ.NEXTVAL,'esporadica',3,3);


---------------------INTERTAR CUADRIILLAS---------------------------
INSERT INTO CUADRILLAS(ID_CUADRILLA,BORRADO,NOMBRE) VALUES (CUADRILLAS_SEQ.NEXTVAL,0,'Alfa');
INSERT INTO CUADRILLAS(ID_CUADRILLA,BORRADO,NOMBRE) VALUES (CUADRILLAS_SEQ.NEXTVAL,0,'Beta');
INSERT INTO CUADRILLAS(ID_CUADRILLA,BORRADO,NOMBRE) VALUES (CUADRILLAS_SEQ.NEXTVAL,0,'Gama');

---------------------INTERTAR REPORTE DE DAÑO---------------------------
INSERT INTO INCIDENCIAS (ID_INCIDENCIA,ID_CLIENTE,ID_TIPO_INCIDENCIA,DESCRIPCION,FECHA_REGISTRO) VALUES(INCIDENCIAS_SEQ.nextval,1,2,'El servicio falla al medio dia',sysdate);
INSERT INTO INCIDENCIAS (ID_INCIDENCIA,ID_CLIENTE,ID_TIPO_INCIDENCIA,DESCRIPCION,FECHA_REGISTRO) VALUES(INCIDENCIAS_SEQ.nextval,2,3,'Se entrecortan las llamadas en ocaciones',sysdate);
INSERT INTO INCIDENCIAS (ID_INCIDENCIA,ID_CLIENTE,ID_TIPO_INCIDENCIA,DESCRIPCION,FECHA_REGISTRO) VALUES(INCIDENCIAS_SEQ.nextval,1,1,'No hay servicio de telefonia',sysdate);
INSERT INTO INCIDENCIAS (ID_INCIDENCIA,ID_CLIENTE,ID_TIPO_INCIDENCIA,DESCRIPCION,FECHA_REGISTRO) VALUES(INCIDENCIAS_SEQ.nextval,1,1,'No hay servicio de telefonia',TO_DATE('2021-06-2T15:34:49Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));

UPDATE INCIDENCIAS SET FECHA_REGISTRO=TO_DATE('2021-06-1T5:50:14Z',  'YYYY-MM-DD"T"HH24:MI:SS"Z"') WHERE ID_INCIDENCIA=19;
UPDATE INCIDENCIAS SET FECHA_REGISTRO=TO_DATE('2021-06-2T13:23:19Z',  'YYYY-MM-DD"T"HH24:MI:SS"Z"') WHERE ID_INCIDENCIA=22;
UPDATE INCIDENCIAS SET FECHA_REGISTRO=TO_DATE('2021-06-2T18:34:49Z',  'YYYY-MM-DD"T"HH24:MI:SS"Z"') WHERE ID_INCIDENCIA=23;

---------------------INSERTAR ORDENES DE ATENCION---------------------------------
INSERT INTO ORDENES_ATENCION (ID_ORDEN_ATENCION,ID_INCIDENCIA,NUMERO_ORDEN,AGENDADO) VALUES (ORDENES_ATENCION_SEQ.NEXTVAL,26 ,'2bbe6a82-072e-4114-88f6-f9ed2d504161',0);
INSERT INTO ORDENES_ATENCION (ID_ORDEN_ATENCION,ID_INCIDENCIA,NUMERO_ORDEN,AGENDADO) VALUES (ORDENES_ATENCION_SEQ.NEXTVAL,29 ,'07f86c8b-1ef5-411e-b6aa-91c907b0eb9b',0);
INSERT INTO ORDENES_ATENCION (ID_ORDEN_ATENCION,ID_INCIDENCIA,NUMERO_ORDEN,AGENDADO) VALUES (ORDENES_ATENCION_SEQ.NEXTVAL,30 ,'0f468844-49ea-4dd5-a980-a5cf20ca0345',0);
INSERT INTO ORDENES_ATENCION (ID_ORDEN_ATENCION,ID_INCIDENCIA,NUMERO_ORDEN,AGENDADO) VALUES (ORDENES_ATENCION_SEQ.NEXTVAL,31 ,'51ebbda4-ca19-4a4c-859c-31bc6891cde7',0);
INSERT INTO ORDENES_ATENCION (ID_ORDEN_ATENCION,ID_INCIDENCIA,NUMERO_ORDEN,AGENDADO) VALUES (ORDENES_ATENCION_SEQ.NEXTVAL,32,'f9d957ef-524d-4961-9aef-a128de507bb3',0);
INSERT INTO ORDENES_ATENCION (ID_ORDEN_ATENCION,ID_INCIDENCIA,NUMERO_ORDEN,AGENDADO) VALUES (ORDENES_ATENCION_SEQ.NEXTVAL,33,'b7dd7dfc-d14a-4541-bd05-5c58e6b0c035',0);
INSERT INTO ORDENES_ATENCION (ID_ORDEN_ATENCION,ID_INCIDENCIA,NUMERO_ORDEN,AGENDADO) VALUES (ORDENES_ATENCION_SEQ.NEXTVAL,34,'38f6bd47-163c-40e6-93e8-0eb0195ec45c',0);

----------------------------------INSERTAR AGENDA--------------------------------------
INSERT INTO AGENDAS (ID_AGENDA,ID_ORDEN_ATENCION,ID_TECNICO,H_INICIO,H_FINAL,FECHA) VALUES (AGENDAS_SEQ.NEXTVAL,4,2,TO_DATE('2021-06-29T8:00','YYYY-MM-DD"T"HH24:MI'),TO_DATE('2021-06-29T12:00','YYYY-MM-DD"T"HH24:MI'),TO_DATE('2021/06/29','YYYY-MM-DD'));
INSERT INTO AGENDAS (ID_AGENDA,ID_ORDEN_ATENCION,ID_TECNICO,H_INICIO,H_FINAL,FECHA) VALUES (AGENDAS_SEQ.NEXTVAL,1,2,TO_DATE('2021-06-29T13:00','YYYY-MM-DD"T"HH24:MI'),TO_DATE('2021-06-29T14:00','YYYY-MM-DD"T"HH24:MI'),TO_DATE('2021/06/29','YYYY-MM-DD'));
INSERT INTO AGENDAS (ID_AGENDA,ID_ORDEN_ATENCION,ID_TECNICO,H_INICIO,H_FINAL,FECHA) VALUES (AGENDAS_SEQ.NEXTVAL,2,2,TO_DATE('2021-06-29T14:00','YYYY-MM-DD"T"HH24:MI'),TO_DATE('2021-06-29T16:00','YYYY-MM-DD"T"HH24:MI'),TO_DATE('2021/06/29','YYYY-MM-DD'));
INSERT INTO AGENDAS (ID_AGENDA,ID_ORDEN_ATENCION,ID_TECNICO,H_INICIO,H_FINAL,FECHA) VALUES (AGENDAS_SEQ.NEXTVAL,3,2,TO_DATE('2021-06-30T8:00','YYYY-MM-DD"T"HH24:MI'),TO_DATE('2021-06-30T10:00','YYYY-MM-DD"T"HH24:MI'),TO_DATE('2021/06/30','YYYY-MM-DD'));

INSERT INTO AGENDAS (ID_AGENDA,ID_ORDEN_ATENCION,ID_TECNICO,H_INICIO,H_FINAL,FECHA) VALUES (AGENDAS_SEQ.NEXTVAL,5,3,TO_DATE('2021-06-29T8:00','YYYY-MM-DD"T"HH24:MI'),TO_DATE('2021-06-27T10:00','YYYY-MM-DD"T"HH24:MI'),TO_DATE('2021/06/29','YYYY-MM-DD'));
INSERT INTO AGENDAS (ID_AGENDA,ID_ORDEN_ATENCION,ID_TECNICO,H_INICIO,H_FINAL,FECHA) VALUES (AGENDAS_SEQ.NEXTVAL,6,3,TO_DATE('2021-06-29T10:00','YYYY-MM-DD"T"HH24:MI'),TO_DATE('2021-06-27T12:00','YYYY-MM-DD"T"HH24:MI'),TO_DATE('2021/06/29','YYYY-MM-DD'));

