
-------------------------------TIPOS INCIDENCIA-------------------------------------
INSERT INTO TIPOS_INCIDENCIA (ID_TIPO_INCIDENCIA,NOMBRE,PRIORIDAD,TIEMPO_ATENCION) VALUES (nextval('TIPOS_INCIDENCIA_SEQ'),'total',1,1);
INSERT INTO TIPOS_INCIDENCIA (ID_TIPO_INCIDENCIA,NOMBRE,PRIORIDAD,TIEMPO_ATENCION) VALUES (nextval('TIPOS_INCIDENCIA_SEQ'),'parcial',2,2);
INSERT INTO TIPOS_INCIDENCIA (ID_TIPO_INCIDENCIA,NOMBRE,PRIORIDAD,TIEMPO_ATENCION) VALUES (nextval('TIPOS_INCIDENCIA_SEQ'),'esporadica',3,3);


