
-------------------------TIPOS DE CLIENTE-------------------------------------------
INSERT INTO TIPOS_CLIENTE (ID_TIPO_CLIENTE,NOMBRE,PRIORIDAD) VALUES (nextval('TIPOS_CLIENTE_SEQ'),'Hospitales',1);
INSERT INTO TIPOS_CLIENTE (ID_TIPO_CLIENTE,NOMBRE,PRIORIDAD) VALUES (nextval('TIPOS_CLIENTE_SEQ'),'Entidades gubernamentales',2);
INSERT INTO TIPOS_CLIENTE (ID_TIPO_CLIENTE,NOMBRE,PRIORIDAD) VALUES (nextval('TIPOS_CLIENTE_SEQ'),'Personas VIP',3);
INSERT INTO TIPOS_CLIENTE (ID_TIPO_CLIENTE,NOMBRE,PRIORIDAD) VALUES (nextval('TIPOS_CLIENTE_SEQ'),'Empresas de taxi',4);
INSERT INTO TIPOS_CLIENTE (ID_TIPO_CLIENTE,NOMBRE,PRIORIDAD) VALUES (nextval('TIPOS_CLIENTE_SEQ'),'Persona normal',5);

